# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Album-clipping-editor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HXPhotoPicker' ,'~> 3.3.2'
  pod 'JSBadgeView', '~> 2.0.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'OpenCV2', '~> 4.3.0'
  # Pods for Album-clipping-editor

  target 'Album-clipping-editorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Album-clipping-editorUITests' do
    # Pods for testing
  end

end
